<?phpinclude_once APPPATH."libraries/core/Crmmodel.php";class Advertisescompanies_model extends Crmmodel{	public function __construct(){		parent::__construct();	}
		public function get_ds(){		$this->db->select('SQL_CALC_FOUND_ROWS _advertisescompanies.rid as rid, 							_advertisescompanies.company_name as company_name,  							_advertisescompanies.company_type as company_type,  							DATE_FORMAT(_advertisescompanies.modifyDT, \'%d.%m.%Y\') as modifyDT, 							_advertisescompanies.descr as descr, _advertisescompanies.archive', False);		$this->db->from('_advertisescompanies');		if($searchRule = element('like', $this->ci->get_session('searchrule'), null)) $this->db->like($searchRule);		if($searchRule = element('where', $this->ci->get_session('searchrule'), null)) $this->db->where($searchRule);		if($searchRule = element('having', $this->ci->get_session('searchrule'), null)) $this->db->having($searchRule);		if($sort = $this->ci->get_session('sort'))	$this->db->orderby($sort['c'], $sort['r']);		$this->db->limit($this->ci->config->item('crm_grid_limit'), element('p', $this->ci->a_uri_assoc, null));		$query = $this->db_get('_advertisessources');		return $query->num_rows()?$query->result():array();	}
	
	public function get_edit($rid){		$this->db->select('_advertisescompanies.rid as rid, 							_advertisescompanies.company_name as company_name,  							_advertisescompanies.company_type as company_type,  							_advertisescompanies.modifyDT as modifyDT, 							_advertisescompanies.descr as descr, _advertisescompanies.owner_users_rid,							_advertisescompanies.archive', False);		$this->db->from('_advertisescompanies');		$this->db->where(array('_advertisescompanies.rid'=>$rid));		$query = $this->db_get('_advertisescompanies');		return $query->num_rows()?$query->row():False;	}
		public function create_record(){		$ins_arr = array('company_name'=>$this->ci->input->post('company_name'),							'company_type'=>$this->ci->input->post('company_type'),							'descr'=>$this->ci->input->post('descr'),							'archive'=>$this->ci->input->post('archive'),							'owner_users_rid'=>get_curr_urid(),							'modifier_users_rid'=>get_curr_urid());		$this->db->set('createDT', 'now()', False);		$this->db->set('modifyDT', 'now()', False);		$this->db->trans_begin();		$this->db->insert('_advertisescompanies', $ins_arr);		$insRid = $this->db->insert_id();		if ($this->db->trans_status() === FALSE){    		$this->db->trans_rollback();    		return False;		}else{    		$this->db->trans_commit();    		return $insRid;		}			}
	
	public function update_record(){		$update_arr = array('company_name'=>$this->ci->input->post('company_name'),							'company_type'=>$this->ci->input->post('company_type'),							'descr'=>$this->ci->input->post('descr'),							'archive'=>$this->ci->input->post('archive'),							'modifier_users_rid'=>get_curr_urid());		$this->db->set('modifyDT', 'now()', False);
		$this->db->trans_begin();		$this->db->update('_advertisescompanies', $update_arr, array('rid'=>$this->ci->input->post('rid')));		if ($this->db->trans_status() === FALSE){    		$this->db->trans_rollback();    		return False;		}else{    		$this->db->trans_commit();    		return True;		}			}
	public function remove_items(){		$this->db->trans_begin();		foreach($this->ci->input->post('row') as $rid){			$this->db->delete('_advertisescompanies', array('rid'=>$rid));			}		if ($this->db->trans_status() === FALSE){    		$this->db->trans_rollback();    		return False;		}else{    		$this->db->trans_commit();    		return True;		}			}			public function get_companyname_byrid($rid){		$this->db->select('_advertisescompanies.company_name as company_name', False);		$this->db->from('_advertisescompanies');		$this->db->where(array('rid'=>$rid));		$this->db->order_by('company_name');		$query = $this->db->get();		return $query->num_rows()?$query->row()->company_name:null; 	}			public function move_record(){		$update_doc = array('owner_users_rid'=>get_urid_byemprid($this->ci->input->post('_employeers_rid')));		$this->db->set('modifyDT', 'now()', False);		$this->db->trans_begin();		$this->db->update('_advertisescompanies', $update_doc, array('_advertisescompanies.rid'=>$this->ci->input->post('rid')));		if ($this->db->trans_status() === FALSE){    		$this->db->trans_rollback();    		return False;		}else{    		$this->db->trans_commit();    		return $this->ci->input->post('rid');		}			}	}
?>